"""Data: recording play, and the three-stage curriculum that turns it into a controller.

Lumine is trained on three corpora with three different jobs:

===========  ==========  ==========================================================
stage        scale       what it teaches
===========  ==========  ==========================================================
``pretrain`` 1731 h      action primitives -- raw ``(frame -> action)`` behaviour cloning
``instruct``  200 h      instruction following -- condition the same policy on language
``reason``     15 h      adaptive thinking -- when to stop and reason, and what to conclude
===========  ==========  ==========================================================

The ratio is the point, and it is extreme.  Reasoning data is 0.8% of the corpus; almost
all of the learning is low-level competence, and the expensive model is reserved for the
rare moments that need it.  That is why this project's VLM is a planner over skills rather
than a source of keystrokes.

Honest note on our own numbers: we cannot collect 1731 hours, so the sandbox corpus is
minutes long, and the action head it produces is a demonstration of the pipeline rather
than a competitive controller.  Storage maths for the real thing is in the README.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator

import numpy as np

from .config import DataConfig
from .types import Action, KEYS, NUM_KEYS


@dataclass(frozen=True)
class StageSpec:
    name: str
    needs_instruction: bool
    needs_reasoning: bool
    target_hours: float
    description: str


CURRICULUM: tuple[StageSpec, ...] = (
    StageSpec("pretrain", False, False, 1731.0,
              "Raw gameplay. Behaviour-clone the action primitives: given a frame, emit keys."),
    StageSpec("instruct", True, False, 200.0,
              "Same frames, now paired with a natural-language order, so control is grounded "
              "in language rather than in whatever the demonstrator happened to be doing."),
    StageSpec("reason", True, True, 15.0,
              "Frames where thinking paid off, paired with the reasoning that resolved them. "
              "Trains the policy to invoke and use reasoning adaptively."),
)

STAGE_BY_NAME: dict[str, StageSpec] = {s.name: s for s in CURRICULUM}


# --------------------------------------------------------------------------------------
# Recording
# --------------------------------------------------------------------------------------


@dataclass
class Sample:
    """One (frame, action) pair plus whatever supervision accompanies it."""

    frame: np.ndarray                 # (H, W) uint8 grayscale
    action: np.ndarray                # float32 vector, see Action.to_vector
    instruction: str = ""
    reasoning: str = ""
    skill: str = ""
    t: float = 0.0


@dataclass
class Recorder:
    """Streams samples into ``.npz`` shards.

    Frames are stored as single-channel 160x90 ``uint8`` for two reasons: the action head
    only ever needs coarse spatial information to emit keystrokes, and colour triples the
    archive.  The colour original is never lost -- the game is replayable.
    """

    cfg: DataConfig = field(default_factory=DataConfig)
    stage: str = "pretrain"
    frame_width: int = 160
    frame_height: int = 90
    record_hz: float = 10.0
    #: Set when the corpus is generated by the scripted teacher rather than a human.
    source: str = "scripted"

    _frames: list[np.ndarray] = field(default_factory=list)
    _actions: list[np.ndarray] = field(default_factory=list)
    _instructions: list[str] = field(default_factory=list)
    _reasonings: list[str] = field(default_factory=list)
    _skills: list[str] = field(default_factory=list)
    _shard_index: int = 0
    _last_record_t: float = -1e9
    _episode: int = 0

    @property
    def root(self) -> Path:
        return Path(self.cfg.root) / self.stage

    def maybe_add(self, image: np.ndarray, action: Action, t: float,
                  instruction: str = "", reasoning: str = "", skill: str = "") -> bool:
        """Record one sample, respecting ``record_hz``.  Returns True if it was stored."""
        if t - self._last_record_t < 1.0 / max(1e-6, self.record_hz):
            return False
        self._last_record_t = t
        self._frames.append(_to_gray(image, self.frame_width, self.frame_height))
        self._actions.append(action.to_vector())
        self._instructions.append(instruction)
        self._reasonings.append(reasoning)
        self._skills.append(skill)
        if len(self._frames) >= self.cfg.shard_size:
            self.flush()
        return True

    def new_episode(self) -> None:
        self._episode += 1
        self._last_record_t = -1e9

    def flush(self) -> Path | None:
        if not self._frames:
            return None
        self.root.mkdir(parents=True, exist_ok=True)
        path = self.root / f"shard-{self._shard_index:05d}.npz"
        np.savez_compressed(
            path,
            frames=np.stack(self._frames),
            actions=np.stack(self._actions),
            instructions=np.array(self._instructions, dtype=object),
            reasonings=np.array(self._reasonings, dtype=object),
            skills=np.array(self._skills, dtype=object),
            meta=json.dumps({"stage": self.stage, "source": self.source,
                             "hz": self.record_hz, "keys": list(KEYS),
                             "episodes": self._episode, "created": time.time()}),
        )
        self._frames.clear()
        self._actions.clear()
        self._instructions.clear()
        self._reasonings.clear()
        self._skills.clear()
        self._shard_index += 1
        return path

    def close(self) -> None:
        self.flush()


def _to_gray(image: np.ndarray, width: int, height: int) -> np.ndarray:
    import cv2

    small = cv2.resize(image, (width, height), interpolation=cv2.INTER_AREA)
    if small.ndim == 3:
        small = cv2.cvtColor(small, cv2.COLOR_RGB2GRAY)
    return small.astype(np.uint8)


# --------------------------------------------------------------------------------------
# Reading
# --------------------------------------------------------------------------------------


@dataclass
class ShardReader:
    paths: list[Path]

    @classmethod
    def discover(cls, root: str | Path, stage: str) -> "ShardReader":
        p = Path(root) / stage
        return cls(sorted(p.glob("shard-*.npz")))

    def __len__(self) -> int:
        total = 0
        for p in self.paths:
            with np.load(p, allow_pickle=True) as z:
                total += int(z["frames"].shape[0])
        return total

    def __iter__(self) -> Iterator[dict[str, np.ndarray]]:
        for p in self.paths:
            with np.load(p, allow_pickle=True) as z:
                yield {
                    "frames": z["frames"],
                    "actions": z["actions"],
                    "instructions": np.asarray(z["instructions"], dtype=str),
                    "reasonings": np.asarray(z["reasonings"], dtype=str),
                    "skills": np.asarray(z["skills"], dtype=str),
                }

    def load_all(self, limit: int | None = None) -> dict[str, np.ndarray]:
        frames, actions, instructions, reasonings, skills = [], [], [], [], []
        for shard in self:
            frames.append(shard["frames"])
            actions.append(shard["actions"])
            instructions.append(shard["instructions"])
            reasonings.append(shard["reasonings"])
            skills.append(shard["skills"])
            if limit and sum(len(f) for f in frames) >= limit:
                break
        if not frames:
            n = 0
            return {"frames": np.zeros((0, 90, 160), np.uint8),
                    "actions": np.zeros((0, NUM_KEYS + 5), np.float32),
                    "instructions": np.zeros(0, dtype=str),
                    "reasonings": np.zeros(0, dtype=str),
                    "skills": np.zeros(0, dtype=str)}
        out = {
            "frames": np.concatenate(frames),
            "actions": np.concatenate(actions).astype(np.float32),
            "instructions": np.concatenate(instructions),
            "reasonings": np.concatenate(reasonings),
            "skills": np.concatenate(skills),
        }
        if limit:
            for k in out:
                out[k] = out[k][:limit]
        return out


def corpus_report(root: str | Path) -> dict[str, Any]:
    """Summarise every stage: shards, frames, and the hours they represent."""
    root = Path(root)
    out: dict[str, Any] = {}
    for stage in STAGE_BY_NAME:
        reader = ShardReader.discover(root, stage)
        frames = len(reader) if reader.paths else 0
        hours = frames / 10.0 / 3600.0          # recorded at 10 Hz
        target = STAGE_BY_NAME[stage].target_hours
        out[stage] = {
            "shards": len(reader.paths),
            "frames": frames,
            "hours": round(hours, 4),
            "target_hours": target,
            "coverage": round(hours / target, 6) if target else 0.0,
        }
    return out


def format_corpus_report(report: dict[str, Any]) -> str:
    lines = ["| stage | shards | frames | hours | Lumine target | coverage |",
             "|---|---|---|---|---|---|"]
    for stage, r in report.items():
        lines.append(f"| {stage} | {r['shards']} | {r['frames']:,} | {r['hours']:.4f} | "
                     f"{r['target_hours']:,.0f} h | {r['coverage'] * 100:.4f}% |")
    return "\n".join(lines)
